x = input('digite qualquer coisa: ')
print('tipo: ',type(x))
print('string: ', x.isalpha())
print('numero: ',x.isnumeric())
print('alfanumérico: ',x.isalnum())
print('so tem espaço: ',x.isspace())
print('so letra maiuscula: ',x.isupper())
print('so letra minuscula: ',x.islower())